name: annotated
version: 0.1.0
description: Annotation support for source code analysis and generation.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://craft-dart.github.io

environment:
  sdk: '>=1.21.0 <2.0.0'

dev_dependencies:
  test: ^0.12.0
